
server:
  port: 8099
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: opendoc_user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.9:3306/qdz?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
#MyBatis
mybatis-plus:
  #mapper-locations: classpath:/mapper/*Mapper.xml
  #type-enums-package: com.git.enums.BaseEnum
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.git.pojo
  global-config:
    db-config:
      id-type: auto #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      field-strategy: not_null #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    refresh: true #刷新mapper 调试神器
  configuration:
    map-underscore-to-camel-case: true #驼峰下划线转换
    cache-enabled: false
    #不加这个查询数据为空时，字段将被隐藏
    default-statement-timeout: 5000
